export type Game = {
  _id: string;
  title: string;
  type: string[];
  releaseDate: string;
  platform: string;
  maxPlayer?: number;
  total: number;
  status?: string;
  priceDefault: number;
  priceDeposit?: number;
  discount?: number;
  priceOffical: number;
  shortDescription?: string;
  note?: string;
  imageDefault: string;
  imageList?: string[];
  videoList?: string[];
  description: string[];
};
